//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace peshitta.nl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("peshitta.nl.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peshitta.nl.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de peshitta.nl Bijbelvertaling.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Online Bijbelvertaling.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bijbel Online, God, JHWH, Jezus, Jeshua, Christus, Messias, Koninkrijk, Aramees, Arameeër, Peshitta, Kerk, Geloof, Gemeente, apostel, Maria, Bijbel Kopen, Evangelie, De Boodschap, Johannes, Matteus, Markus, Marcus, Lukas, Lucas, Petrus, Timoteüs.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bijbel, God, Jahweh, JHWH, Jezus, Jeshua, Christus, Messias, Aramees, Peshitta, Evangelie, Kerk, Religie, Geloof, Gemeente, dogma, sekte, waarheid, apostel, drie-eenheid, drieëenheid, Maria, Bijbel Kopen.
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alles over de Peshitta Bijbelvertaling van het Nieuwe Testament.
        /// </summary>
        internal static string AboutVertaling {
            get {
                return ResourceManager.GetString("AboutVertaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2001 vertaling gerelateerde links.
        /// </summary>
        internal static string links2001 {
            get {
                return ResourceManager.GetString("links2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to peshitta.nl gerelateerde links.
        /// </summary>
        internal static string linksTitlePeshitta {
            get {
                return ResourceManager.GetString("linksTitlePeshitta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Bijbelvertaling van het Syrisch-Aramese NT, de Peshitta.
        /// </summary>
        internal static string PeshittaDescr {
            get {
                return ResourceManager.GetString("PeshittaDescr", resourceCulture);
            }
        }
    }
}
